version: '3.3'

services:
   elasticsearch:
     build: .
     volumes:
       - esdata:/usr/share/elasticsearch/data
     expose:
       - "9200"
       - "9300"
     restart: always
     environment:
       - "discovery.type=single-node"
       - "repositories.url.allowed_urls=https://storage.googleapis.com/*"
       - "xpack.security.enabled=false"
   
   restapi:
     image: quay.io/opentargets/rest_api
     expose:
       - "80"
       - "443"
     privileged: true
     restart: always
     environment:
       - ELASTICSEARCH_URL=http://elasticsearch:9200
       - OPENTARGETS_DATA_VERSION=17.12
     depends_on:
       - elasticsearch
   
   webapp:
     image: quay.io/opentargets/webapp
     expose:
       - "80"
       - "443"
     ports:
       - "80:80"
       - "443:443"
     restart: always
     environment:
       - REST_API_SCHEME=http
       - REST_API_SERVER=restapi
       - REST_API_PORT=80
     depends_on:
       - restapi

volumes:
    esdata: